services:
  - type: web
    name: node-app-activity
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production